### ISSUE TITLE
有關下載器定位的討論

### ISSUE THREAD

**Issue by phillui-37** [phillui-37/epubln_crawler#2]
分享一下想法
- 我打算把現在的下載器做成P2P
  - 我會永久做種(除非我自己的服務器掛了,那是後話)
  - **不會**使用種子,統一使用**DHT+磁力連結** (原因請自己GOOGLE,我這是為了大家安全著想的)
- 也會做一個隨看隨下載的手機APP(就是不用自己手動抓了,就點一下就會下載到手機)
  - 手機APP用不用P2P?其實也是可以的,畢竟考慮到讓大家建伺服器並不可行這點

至於電腦這邊,用下載器的話我會希望大家多少能幫忙做一下種,不然就失去P2P的意義了,當然也有直接從網盤下載的選項,只是網盤失效或限流之類的是無法阻止的,大家也不可能一直讓人補檔的,我比較想藏富於民:)
嘛,由於這個P2P是背景執行的,我會把它設上大量限制,如限速/最大任務數等,只是我也不想強制大家**被逼使用**P2P,所以最終版應該會分成P2P版和網盤版

反正都是分享輕小說,我不希望讓大家東找西找,或者等待補種補檔之類的,統一在這平台發佈,然後誰有能力的也能直接把這repo clone下來自建一個伺服器,甚至改代碼只給自己用也行,那萬一哪天我要把伺服器停機了,大家也不用到處再找一個平台,只要有人能定期做種的話....

**Comment by phillui-37** [comment]
沒人回應的話我就做兩個版本了,一個是網盤版一個是BT版,然後所有更新以BT版為準

**Comment by sunyu97** [comment]
对不起来晚了.
是这样的, 我觉得关于共享的部分可以考虑使用Syncthing 之类的工具, 客户端可以使用只读key, 数据下载同样还是p2p, 不过大陆用户很可能需要斗墙... (幸好肉身翻墙完成... 
我自己的轻小说/漫画/其他书是有使用Calibre整理, 自家NAS上COPS出来使用的用法, 如果需要补种可以帮忙.

**Comment by phillui-37** [comment]
我打算下載的全部在數據庫保存一份磁連，而做種的話手機app不強制，pc的客戶端強制上傳

資料庫記錄運用github release同步，至於國內我不考慮，因為用百度盤或者上輕國/貼吧都比在我這下載方便

補種應該不需要，我從輕國抓回來做簡轉繁就可以了，我比較需要一起寫的小伙伴（拖

**Comment by phillui-37** [comment]
共享用syncthing在pc可以，在手機就不行了

**Comment by sunyu97** [comment]
android一边还是可以用的...赋权成功的话...
至于简繁转换, 我现在用的方式是替换字体, 有人做了Noto Sans CJK的字形(ttf), 用户直接使用这个字体就有繁转简了... 不过信息熵上去了再回来就难了, 毕竟有一个简体字可能对应多个繁体字的问题... 
等等, 你的分享部分只是数据库啊, 何不直接web host 开个数据库接口算了...

**Comment by phillui-37** [comment]
我用的是SQLite啊,而且我的服務器不打算對外開放接口

P2P倒是可以,web host就算了

簡繁的話我倒是可以直接上雙語的選擇

**Comment by phillui-37** [comment]
android我打算用flutter配合java的bt與epub庫寫...

**Comment by phillui-37** [comment]
我會永久做種直到我的服務器掛掉

**Comment by phillui-37** [comment]
目前因為Java bt庫實現不完善,而libtorrent要弄JNI有點麻煩,加上沒解決在Android上使用Selenium的頭緒,暫時先擱置討論,先把現在版本的TODO做完並完善再考慮以後的事
